### ISSUE TITLE
`yo chrome-extension` broke on my mechine

### ISSUE THREAD

**Issue by githubutilities** [yeoman/generator-chrome-extension#103]
after installing generator-chrome-extension, I try to run `yo chrome-extension` and I got this error.

```sh
/usr/local/lib/node_modules/generator-chrome-extension/node_modules/yeoman-generator/lib/base.js:445
  this.env.sharedFs.on('change', writeFiles);
                    ^
TypeError: undefined is not a function
    at run (/usr/local/lib/node_modules/generator-chrome-extension/node_modules/yeoman-generator/lib/base.js:445:21)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:330:20)
    at /usr/local/lib/node_modules/yo/lib/cli.js:91:9
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:50:12)
    at init (/usr/local/lib/node_modules/yo/lib/cli.js:66:7)
    at pre (/usr/local/lib/node_modules/yo/lib/cli.js:53:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:155:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by ragingwind** [comment]
Search http://stackoverflow.com/questions/28536753/yo-polymer-building-error

**Comment by githubutilities** [comment]
Seems that my `yo` is outdated. Thanks
