### ISSUE TITLE
Cannot generate app

### ISSUE THREAD

**Issue by vhchung** [yeoman/generator-chrome-extension#123]
When I run the command `yo chrome-extension`, I received this error:

```
/usr/local/lib/node_modules/generator-chrome-extension/node_modules/yeoman-generator/lib/base.js:474
  this.env.sharedFs.on('change', writeFiles);
                    ^

TypeError: this.env.sharedFs.on is not a function
    at run (/usr/local/lib/node_modules/generator-chrome-extension/node_modules/yeoman-generator/lib/base.js:474:21)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:319:20)
    at /usr/local/lib/node_modules/yo/lib/cli.js:87:9
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:49:32)
    at init (/usr/local/lib/node_modules/yo/lib/cli.js:66:7)
    at pre (/usr/local/lib/node_modules/yo/lib/cli.js:53:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:156:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
```

**Comment by arthurvr** [comment]
Hmm, can you check the version of `yo` and `generator-chrome-extension` you're using?

**Comment by ragingwind** [comment]
Could you try to re-install after `npm cache clean`?

**Comment by vhchung** [comment]
Well, I updated `yo` and then re-install the generator. Now it works. Thankyou for your support :)
