### ISSUE TITLE
Fresh repo clone doesn't work

### ISSUE THREAD

**Issue by bartq** [yeoman/generator-chrome-extension#143]
Here's the result:
```
$ gulp watch
module.js:327
    throw err;
    ^

Error: Cannot find module 'clone-stats'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/vinyl/index.js:3:18)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

```

**Comment by ragingwind** [comment]
It's your local problem related to npm and gulp.
