### ISSUE TITLE
Manifest has no background property

### ISSUE THREAD

**Issue by onmyway133** [yeoman/generator-chrome-extension#167]
Hi, I'm about to build my extension https://github.com/onmyway133/github-extended. I only have content script. `gulp build` gives me `Manifest has no background property`

```
Users/khoa/XcodeProject3/github-extended/node_modules/gulp-chrome-manifest/index.js:58
				throw new Error('Manifest has no background property');
				^

Error: Manifest has no background property
    at DestroyableTransform._transform (/Users/khoa/XcodeProject3/github-extended/node_modules/gulp-chrome-manifest/index.js:58:11)
    at DestroyableTransform.Transform._read (/Users/khoa/XcodeProject3/github-extended/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/khoa/XcodeProject3/github-extended/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/khoa/XcodeProject3/github-extended/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Users/khoa/XcodeProject3/github-extended/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/Users/khoa/XcodeProject3/github-extended/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at write (/Users/khoa/XcodeProject3/github-extended/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/khoa/XcodeProject3/github-extended/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/khoa/XcodeProject3/github-extended/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:80:13)
```

How to work around this? Thanks

**Comment by ragingwind** [comment]
Do not pass `background` option to `gulp-chrome-manifest`. remove it
