### ISSUE TITLE
Error: watch ENOSPC

### ISSUE THREAD

**Issue by strongant** [yeoman/generator-chrome-extension#172]
Error: watch /home/devbwh/study/chrome/proj/pfplugin/app/ ENOSPC
    at exports._errnoException (util.js:873:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at Gaze._watchDir (/home/devbwh/study/chrome/proj/pfplugin/node_modules/gaze/lib/gaze.js:289:30)
    at /home/devbwh/study/chrome/proj/pfplugin/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/home/devbwh/study/chrome/proj/pfplugin/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/home/devbwh/study/chrome/proj/pfplugin/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/home/devbwh/study/chrome/proj/pfplugin/node_modules/gaze/lib/gaze.js:354:10)
    at Gaze.add (/home/devbwh/study/chrome/proj/pfplugin/node_modules/gaze/lib/gaze.js:177:8)
    at new Gaze (/home/devbwh/study/chrome/proj/pfplugin/node_modules/gaze/lib/gaze.js:74:10)

**Comment by strongant** [comment]
Thanks for the solution ! :)
https://github.com/shama/gaze/issues/163
