### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist

### ISSUE THREAD

**Issue by snowman** [yeoman/generator-chrome-extension#226]
Steps to reproduce
```
yarn global add yo gulp-cli bower
yarn global add generator-chrome-extension
mkdir /tmp/chrome_extension && cd $_
yo chrome-extension
```

output
```
? Choose your style of DSL BDD
? What would you like to call this extension? my new chrome extension
? How would you like to describe this extension? My Chrome Extension
? Would you like to use UI Action? No
? Would you like more UI Features?
? Would you like to set permissions?
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: $HOME/.config/yarn/global/node_modules/generator-chrome-extension/node_modules/@babel/polyfill/dist/polyfill.min.js
    at EditionInterface.exports._copySingle ($HOME/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy ($HOME/.config/yarn/global/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at constructor.babel ($HOME/.config/yarn/global/node_modules/generator-chrome-extension/app/index.js:294:13)
    at Object.<anonymous> ($HOME/.config/yarn/global/node_modules/yeoman-generator/lib/base.js:439:23)
    at $HOME/.config/yarn/global/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at $HOME/.config/yarn/global/node_modules/run-async/index.js:26:19
    at $HOME/.config/yarn/global/node_modules/yeoman-generator/lib/base.js:440:9
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:130:23)
```

Build OS Environment
```
$ nvm ls
         v8.9.0
       v10.18.0
       v10.18.1
->     v12.14.0
         system

$ npm --version
6.13.4

yarn --version
1.22.5
```

**Comment by snowman** [comment]
Fixed by

```
yarn global remove generator-chrome-extension
npm install --global generator-chrome-extension
```
