### ISSUE TITLE
Error while installing Cannot find module 'es5-ext/lib/Object/descriptor' possibly due to mocha

### ISSUE THREAD

**Issue by smurfpandey** [yeoman/generator-chrome-extension#44]
I am getting an error while using this generator. This is the output from the command line. I am running it on Windows 8

  create app/manifest.json
   create app/scripts/contentscript.js
   create app/scripts/background.js
   create app/_locales/en/messages.json
   create app/styles/main.css
   create app/images/icon-16.png
   create app/images/icon-128.png
   create package.json
   create bower.json
   create .bowerrc
   create .editorconfig
   create .gitignore
   create .gitattributes
   create .jshintrc
   create Gruntfile.js

module.js:340
    throw err;
    ^
Error: Cannot find module 'es5-ext/lib/Object/descriptor'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Smurf\AppData\Roaming\npm\node_modules\generator-mocha\node_modules\yeoman-generator
\node_modules\inquirer\node_modules\cli-color\lib\index.js:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by Dealazer** [comment]
Solution
Use:
npm install es5-ext
